sudo: required
language: java
sudo: required
dist: trusty
os:
- linux
notifications:
  email: true
before_script:
- "chmod +x build.sh"
- sudo apt-get install -y p7zip-full  ".*-mingw-w64-.*"
script:
- "./build.sh travis"
deploy:
  provider: releases
  skip_cleanup: true 
  api_key:
    secure: imZZydOl6p9WX7cqvj4uou/KrNyCBSvj2LrYUGmAmAWCMndq9IbDVeLj2X4f/SFIsvB3IrzJ2oXiRU2wfLSiCDUlZ5kB+XRd+Pl1k9bXf7afpGh/WxfvkCcGxZ5XispGTnhntbiMsArzajOzti5eMiVcjgeYKLRBCG64bGEiq3xrniuUIVaR2yZlJvMZdEEZe+QioR7Ji77NlcVzPp8hvY3QJwWW0UJibhaZKpXuhSz7LNkoJRZQ8DkRLhsCK3O4xRK1RgeZzzYRuU8sIf7ViPeHX1FUzYSN6KYUx4Ejmjh1FmGlLO55FY06KuiCHk/aAGPtq6nV+febn+9GmUIudGS/wgcJO9pcjeJvTErjwtbzpQIPz9mblGWsmQOZY9QdAOWo9vX2kB0jaJJUmEioxyqjXq2FgwPFPUk0LD0TUUg8vEwBZ7lK5azE8jPm3pRXNoX9IiYcP6LhC28D4wxwDR4qRJvUypRV5vLgQJKPFEkDTFIrMZxG7Ilp/St76dK9vxABOHgeSOezJCuMMG95Qj4ccf9g9j1sCBo8LHLIsL/bADSn4DoF99QzP0P65x4pSuqqx9pcyayrwTnPQpoiXWipn8Pe0sQWCOdzFQv69mnwudhgRIcKGhtSaaIuuM7PzvGYiHvfo3NKSXZ+0YJ3nuoxqvnDm0kLefsfQHneYoU=
  file_glob: true
  file: 
  - build/libs/dist/DDS*.jar
  - build/libs/dist/DDS*-win64.exe
  - build/libs/dist/DDS*-linux64
  on:
    tags: true
