sudo: required
language: java
os:
- linux
notifications:
  email: true
env:
  - LINUX=1
  - WINDOWS=1
script:
- ./build.sh travis
deploy:
  provider: releases
  api_key: ""
  file: "build/libs/dist/*"
  skip_cleanup: true 
  on:
    tags: true